apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bhupen8765/wanderlust-frontend-beta:5.3
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # or "classic" if you prefer
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80               # external port
      targetPort: 5173       # container port
      protocol: TCP
